---
title: ""
editor: visual
---

::::: column-page
## A Note Before You Read (ENG)

At the moment, this page mainly brings together blog posts and short pieces I have written for other websites. My hope, however, is to gradually grow it into a space where I can share my own reflections on teaching, statistics and data science education, systems literacy, academic life, and occasional ideas that don't quite fit anywhere else.

::: {style="font-size: 12px"}
**P.S.** *If you know me personally, you probably know that I love communicating through humor and an excessive number of references to movies, TV shows, internet videos, and song lyrics. Whether I'll have the courage to do the same here remains to be seen.*
:::

## Başlamadan Önce (TR)

Şimdilik bu sayfada ağırlıklı olarak başka web sitelerinde yer alan blog yazılarını bulabilirsiniz. Ancak zamanla burayı; öğretim, istatistik ve veri bilimi eğitimi, sistem okuryazarlığı, akademik yaşam ve bazen de başka hiçbir yere sığmayan düşüncelerimi paylaştığım bir alana dönüştürmeyi umuyorum.

::: {style="font-size: 12px"}
**Not.** *Beni yakından tanıyorsanız, iletişim kurarken çoğunlukla (yer yer ofansif) mizaha başvurduğumu ve film, dizi, internet videosu ile şarkı sözlerine bitmek bilmeyen göndermeler yapmayı sevdiğimi biliyorsunuzdur. Bunu burada da yapacak cesareti bulabilecek miyim, hep birlikte göreceğiz.*
:::

------------------------------------------------------------------------

## Blog Posts

<p>

3.  Does current curricula hinder student understanding of complex global water systems? [{{< fa mug-hot >}}](https://blog.eera-ecer.de/complex-global-water-systems/)

</p>

<p>

2.  Öğretmenlerin dijital yeterlikleri \[Teacher Digital Competencies\]. [{{< fa mug-hot >}}](https://tedmem.org/yazilar-detay/ogretmen-dijital-yeterlikleri)

</p>

<p>

1.  COVID-19 ve dünyada okulların durumu \[COVID-19 and The Status of the Schools Worldwide\]. [{{< fa mug-hot >}}](https://tedmem.org/yazilar-detay/covid-19-ve-dunyada-okullarin-durumu)

</p>
:::::
