---
title: "Workshops and Invited Talks"
description: null
site: distill::distill_website
---

This section includes professional and on-campus workshops and invited talks on miscellaneous topics.

## Workshops

<p>
1. Dogucu, M. & **Demirci, S.** *Disseminating Collaborative and Reproducible Research.* Workshop given at the Department of Statistical Science, University College London. London, UK, Feb 2023 <a href = "https://disseminate-collaborate-reproduce.github.io/schedule/" target="_blank"> `r fontawesome::fa(name = "github")` </a>
</p>

## Invited Talks

<p>
23. Demirci S. *Evolving Landscape of Data Science Education: From Instructor Pedagogy to Policy Perspectives*. Invited talk at California State University, Fullerton, Department of Mathematics, February 2, 2024 <a href = "https://sinemdemirci.github.io/CSUF-research-talk/research-talk.html
" target="_blank"> `r fontawesome::fa(name = "desktop")` </a>
</p>

<p>
22. Demirci S. *Pedagogical Content Knowledge in Data Science Education: An Assessment of Readiness to Teach Data Science in Higher Education*. Invited talk at MAPS Education Forum: Education Research and Dissemination, University College London, July 11, 2023 <a href = "https://sinemdemirci.github.io/maps-ucl-2023/ " target="_blank"> `r fontawesome::fa(name = "desktop")` </a>
</p>

<p>
21. Demirci S. *Pre-service Teachers’ Understanding of Sustainability: Evidence from Türkiye*. Invited talk at UCL ZJU Project Symposium: Promoting education about and for sustainable development, University College London, Institute of Education, Online, June 14, 2023
<a href = "https://sinemdemirci.github.io/ucl-ioe-2023/" target="_blank"> `r fontawesome::fa(name = "desktop")` </a>
</p>

<p>
20. Demirci S. *An Introduction to Systems Thinking and Systems Literacy*. Invited lecture given at the course of PRED 480 Environmental Education, TED University, Department of Elementary Education, Online, May 23, 2023 <a href = "https://sinemdemirci.github.io/sts-tedu/" target="_blank"> `r fontawesome::fa(name = "desktop")` </a>
</p>

<p>
19. Demirci S. *Pedagogical Content Knowledge in Data Science Education: An Assessment of Readiness to Teach Data Science in Higher Education*. Invited talk at Teaching in Mathematical and Statistical Sciences (TMSS) Seminars, University College London, Department of Statistical Science, Online, May 10, 2023<a href = "https://www.ucl.ac.uk/statistics/departmental-seminars/teaching-mathematical-and-statistical-sciences-tmss-seminars" target="_blank"> `r fontawesome::fa(name = "link")`</a>
<a href = "https://sinemdemirci.github.io/pck-ucl-2023/" target="_blank"> `r fontawesome::fa(name = "desktop")` </a>
</p>

<p>
18. Demirci, S. *Middle School Students' Water Systems Literacy: A Multiple Case Study Example*. Invited lecture given at the course of MSE 346 Teaching Complex Systems in Science, Middle East Technical University, Department of Mathematics and Science Education, Online, November 25, 2022
</p>

<p>
17. Demirci, S. *How to Prepare A Conference Paper Presentation*. Invited talk at the course of MSE 599 M.s. Seminar, Middle East Technical University, Department of Mathematics and Science Education, Online, November 11, 2022
</p>

<p>
16. Demirci, S.  *Youth Responsibilities in the Climate Crisis*. Invited talk as a part of Access Project Events (Project Partners: FHI 360, US Embassy Ankara and Turkish Education Association), Online, February 1, 2022
</p>

<p>
15. Demirci, S. iklim degisikliginin bilimi, sebepleri, sonuclari ve cozum onerileri *[Climate change: Science, Causes, Impacts, and Solutions]*. Invited talk as a part of TEDMEM Event at Turkish Education Association , Online, August 20, 2021
</p>

<p>
14. Demirci, S. *How to Prepare A Conference Paper Presentation*. Invited talk at the graduate seminar course, Middle East Technical University, Department of Mathematics and Science Education, Online, 2021
</p>

<p>
13. Demirci, S. *Climate Change: Science, Impacts, and Solutions.* Invited talk as a member of Climate Reality Leadership Corps at the course of MSE 487 Environmental Science, Middle East Technical University, Department of Mathematics and Science Education, December, 2020, Ankara, Turkey
</p>

<p>
12. Demirci, S. *Climate Change: Science, Impacts, and Solutions.* Invited talk as a member of Climate Reality Leadership Corps at the course of MSE 487 Environmental Science, Middle East Technical University, Department of Mathematics and Science Education, Fall 2016, Ankara, Turkey
</p>

<p>
11. Demirci, S. *Climate Change: Science, Impacts, and Solutions.* Invited talk as a member of Climate Reality Leadership Corps at the course of MSE 475 Climate Change Education for Sustainability, Middle East Technical University, Department of Mathematics and Science Education, Spring 2016, Ankara, Turkey
</p>

<p>
1-10. Demirci, S. *Climate Change: Science, Impacts, and Solutions.* A total of 10 talks were given as a member of Climate Reality Leadership Corps at the Middle East Technical University between October 2013 - June 2014, Ankara, Turkey
</p>