---
title: "Project Experiences"
description: null
site: distill::distill_website
---

**Project title:** Exploring Faculty Motivation and Practices Using Universal Design for Instruction in Introductory Statistics/Data Science Classrooms  

**PI:** Dr. Maria Tackett  

**Co-Investigators:** Dr. Sinem Demirci

**Funded by:** American Statistical Association Section on Statistics and Data Science Education Member Initiative Grant

**Role & time spent:** Co-Investigator, 16.12.2024 – Present

---

**Project title:** Exploring the Role of Curiosity in Learning Statistics

**PI:** Dr. Beth Chance  

**Co-Investigators:** Dr. Sinem Demirci, Visruth Srimath Kandali – Cal Poly San Luis Obispo

**Partners/Collaborators:** Ranjani Grove - University of Washington,
David Wilcox - The Lawrenceville School,
Uma Ravat - UC Santa Barbara  

**Role & time spent:** Co-Investigator, 29.10.2024 - Present 

---

**Project title:** Coastal California Classroom Initiative – Exploring the Impact of Sonification on Identifying Skewed Distributions in Introductory Statistics	

**PI:** Jeanine Scaramozzino – Cal Poly, San Luis Obispo  

**Co-Investigators:** Dr. Julia Schedler, Dr. Sinem Demirci – Cal Poly San Luis Obispo  

**Partners/Collaborators:** Donya Ava Behroozi, Annica Wu, Josh Schneider, Aaron C. Liggett, – Cal Poly San Luis Obispo  

**Funded by:** CET Seed Grants  

**Role & time spent:** Co-Investigator, 2024 - 2025 

---
                         
**Project title:**  Pedagogical Content Knowledge in Data Science Education: An Assessment of Readiness to Teach Data Science in Higher Education

**Principle Investigator:** Dr Sinem Demirci

**Co-PI**: Dr Mine Dogucu – University College London

**Collaborators:** Dr Joshua M. Rosenberg – University of Tennessee, Knoxville and Dr Andrew Zieffler – University of Minnesota

**Funded by:** The Scientific and Technological Research Council of Türkiye, TÜBİTAK

**Sponsored by:** University College London

**Time spent:** Principal Investigator, 01.08.2022 - 31.07.2023 

---

**Project title:** Copten Gubreye 3 [<a href = "https://tbm.metu.edu.tr/cevre-egitimleri-projeler/" target="_blank"> From Waste to Fertilizer 3 - Composting</a>]

**Principal Investigator:** Dr. Serap Bilen (METU, Society and Science Application and Research Center) 

**Supported by:** The Scientific and Technological Research Council of Turkey, TUBİTAK

**Role & time spent:** Trainer, 08.04.2019 - 19.04.2019 

**Project No:** 218B226

---

**Project title:** Copten Gubreye! [<a href = "https://tbm.metu.edu.tr/cevre-egitimleri-projeler/" target="_blank"> From Waste to Fertilizer 1 - Composting</a>]

**Principal Investigator:** Dr. Serap Bilen (METU, Society and Science Application and Research Center) 

**Supported by:** The Scientific and Technological Research Council of Turkey, TUBİTAK

**Role & time spent:** Trainer, 09.10.2017 - 30.10.2017 

**Project No:** 117B056

---

**Project title:** University Students’ Beliefs on Human Population Growth 

**Principal Investigator:** Assoc. Prof. Dr. Elvan Sahin (METU, Dept. of Science and Mathematics Education) 

**Supported by:** Scientific Research Projects Coordination Unit, Middle East Technical University

**Role & time spent:** Researcher, 1.1.2013 - 31.12.2013 

**Project No:** BAP-07-03-2013-010

---

**Project title:** In-service Science Teachers’ Teaching Experiences on Atomic Models within the context of History of Science   

**Principal Investigator:**  Assoc. Prof. Dr. Elvan Şahin (METU, Dept. of Science and Mathematics Education)    

**Collaborators:** Prof. Dr. Ayhan Yilmaz - Hacettepe University   

Res. Assist. Sinem Demirci - Middle East Technical University   


**Supported by:** Scientific Research Projects Coordination Unit, Middle East Technical    

**Role & time spent:** Researcher, 1.1.2015 -31.12.2015    

**Project No:** BAP-05-06-2015-001   

---