---
title: "Research Experience"
description: null
site: distill::distill_website
---


# Peer Reviewed Publications


<p>
6. **Demirci, S.**, Reid, A., Teksöz, G., & Sahin, E. (2024). Systems literacy: towards a conspectus and model for environmental and sustainability education. *Environmental Education Research*, 1–36.  <a href = "https://doi.org/10.1080/13504622.2024.2409959" target="_blank"> `r fontawesome::fa(name = "file-lines")`</a>
</p>

<p>
5. Seker S, Sahin E, Hacıeminoğlu E, **Demirci S**. (2024). Do teenagers believe in anthropogenic climate change and take action to tackle it? *Sustainability, 16*(16), 7005. <a href = "https://doi.org/10.3390/su16167005" target="_blank"> `r fontawesome::fa(name = "file-lines")`</a>
</p>

<p>
4. **Demirci, S.**, Sahin E., Teksoz, G. & Marcinkowski, T. J. (2021). Pre-Service teachers’ beliefs on human population growth in the context of education for sustainable development: development and validation of an instrument. *Journal of Teacher Education for Sustainability, 23*(2), 121-142. 
<a href = "https://doi.org/10.2478/jtes-2021-0021" target="_blank"> `r fontawesome::fa(name = "file-lines")`</a>
</p>

<p>
3. **Demirci, S.** & Sahin, E. (2018). An analysis of Turkish middle school science education program placing climate change issues in the context of education for sustainable development. *International Journal of Quality in Education, 2*(1), 13-21. <a href = "https://dergipark.org.tr/en/pub/ijqe/issue/37135/427929" target="_blank"> `r fontawesome::fa(name = "file-lines")`</a>
</p>

<p>
2. **Demirci, S.** (2018). The context of sustainable development in Turkish elementary science curriculum. *International Journal of Quality in Education, 1*(1), 54-61. <a href = "https://dergipark.org.tr/en/pub/ijqe/issue/37117/427577" target="_blank"> `r fontawesome::fa(name = "file-lines")`</a>
</p>

<p>	
1. **Demirci, S.** & Teksöz, G. (2017). Self-Efficacy beliefs on integrating sustainability into profession and daily life: in the words of university students. *International Electronic Journal of Environmental Education, 7*(2), 116-133. 
<a href = "https://files.eric.ed.gov/fulltext/EJ1180990.pdf" target="_blank"> `r fontawesome::fa(name = "file-lines")`</a>
</p>


# Conference Papers/Presentations<sup>†</sup>

<p>
20. **Demirci, S.**, Reid, A., Teksöz, G., & Sahin, E. (2024). A Systems Literacy Approach to Understanding Climate Change Dynamics [Research Panel]. 21st Annual Research Symposium of North American Association for Environmental Education (NAAEE), Pittsburgh, Pennsylvania, U.S.A.
<a href = "https://www.canva.com/design/DAGUyfEn1ik/4WI4OPn0npgjwFU9kQQGZA/view?utm_content=DAGUyfEn1ik&utm_campaign=designshare&utm_medium=link&utm_source=editor" target="_blank"> `r fontawesome::fa(name = "file-lines")`</a>
</p>

<p>
19. **Demirci, S.**, Reid. A, Teksoz, G. & Sahin E. (2023). Systems Literacy as a Key Concept for Quality Education and Agenda 2030. [Roundtable Discussion]. AERA 2023 Annual Meeting, Chicago, Illinois, U.S.A.
  <a href = "https://www.aera.net/Events-Meetings/2023-Annual-Meeting/2023-Annual-Meeting-Program-Information" target="_blank">`r fontawesome::fa(name = "link")`</a>
  <a href= "https://aera23-aera.ipostersessions.com/Default.aspx?s=68-D3-C1-36-1C-76-7C-A5-58-2D-5F-32-C9-A8-2B-FB" target="_blank">`r fontawesome::fa(name = "chart-pie")`</a>
</p>

<p>
18. **Demirci, S.**, Sahin E. & Teksoz, G. (2021). Eight-Graders’ Understanding of Hidden Use of Water and Their Action Strategies for Sustainable Use of Water.[Paper presentation]. European Conference on Educational Research, Geneva, Switzerland 
  <a href = "https://eera-ecer.de/ecer-programmes/conference/26/contribution/50836/" target="_blank">`r fontawesome::fa(name = "link")`</a>
  <a href= "https://drive.google.com/file/d/1BxbggF9j91Ewos7qCIAIm1BsYV86anBr/view?usp=share_link" target="_blank">`r fontawesome::fa(name = "chart-pie")`</a>
  <a href="https://drive.google.com/file/d/1bVVBgeLto3ZAWT_5YbDzMSBMakm0vNaN/view?usp=share_link" target="_blank"> `r fontawesome::fa(name = "desktop")`</a>
</p>

<p>
17. **Demirci, S.**, Sahin E. & Teksoz, G. (2021). Middle School Students’ Perceptions on the Interactions among Water Cycle, Global Warming, and Climate Change. [Paper presentation]. European Conference on Educational Research, Geneva, Switzerland
<a href = "https://eera-ecer.de/ecer-programmes/conference/26/contribution/50838/" target="_blank">`r fontawesome::fa(name = "link")`</a>
<a href= "https://drive.google.com/file/d/1B6fxqdtqb9nmFwyQRCInvKh_NdnTWS99/view?usp=share_link" target="_blank">`r fontawesome::fa(name = "chart-pie")`</a>
  <a href="https://drive.google.com/file/d/1EbV9umjzHm93g8318c3LUbvhkfNGalBY/view?usp=share_link" target="_blank"> `r fontawesome::fa(name = "desktop")`</a>
</p>

<p>
16. **Demirci, S.**, Sahin E. & Teksoz, G. (2020). Redefining Urbanization: in the views of university students. [Paper presentation]. 5th International Symposium on Environment and Morals, Turkey
<a href = "https://i-sem.info/en" target="_blank">`r fontawesome::fa(name = "link")`</a>
<a href = "https://drive.google.com/file/d/1aljEKt9YOpiFoMKLy-eBKi1THG1SxHE8/view?usp=share_link" target="_blank">`r fontawesome::fa(name = "book-bookmark")`</a>
<a href = "https://drive.google.com/file/d/1VeXl5orVvJ6z9YOyk_hoZxe7fYUZYzE3/view?usp=share_link" target="_blank"> `r fontawesome::fa(name = "desktop")`</a>
</p>

<p>
15. **Demirci, S.** & Teksoz, G. (2020). Pre-service Teachers’ Perceptions on the Interactions between COVID-19 Pandemic and the Environment. [Paper presentation]. 5th International Symposium on Environment and Morals, Turkey
<a href = "https://i-sem.info/en" target="_blank">`r fontawesome::fa(name = "link")`</a>
<a href = "https://drive.google.com/file/d/1aljEKt9YOpiFoMKLy-eBKi1THG1SxHE8/view?usp=share_link" target="_blank">`r fontawesome::fa(name = "book-bookmark")`</a>
</p>

<p>
14. **Demirci, S.** & Teksoz, G. (2018). Pre-service Science Teachers’ Skills on Problem/Issue Analysis in Environmental Education. [Paper presentation]. ERPA International Congresses on Education, Istanbul, Turkey
<a href = "https://www.erpacongress.com/upload/dosya/erpa-2018-e-book-of-proceedings-2018_with-isbn_15bc882e42ce0a.pdf" target="_blank">`r fontawesome::fa(name = "book-bookmark")`</a>
<a href = "https://drive.google.com/file/d/1DbYbzMVFpUcWeuZjgNUSWg4xhUAEaLkf/view?usp=share_link" target="_blank">`r fontawesome::fa(name = "desktop")`</a>
</p>

<p>
13. Teksoz, G. & **Demirci, S.** (2017). About the Context of Climate Change Education for Sustainability: In the Words of University Students. [Paper presentation]. 12th Biannual Conference of the European Science Research Association (ESERA), Dublin, Republic of Ireland
<a href = "https://www.dropbox.com/s/ni7rlwfghggu4eq/ESERA-2018-Printed-Programme-14.8.17.pdf?dl=0" target="_blank">`r fontawesome::fa(name = "file-lines")`</a>
<a href = "https://drive.google.com/file/d/1IO96sz0CQaWHzIY460lwP_L0qn5T5k5V/view?usp=share_link" target="_blank">`r fontawesome::fa(name = "desktop")`</a>
</p>

<p>
12. **Demirci, S.**, Kaplan, G., Cengizoglu, S., & Sen, M. (2017). Pre-service teachers’ Understandings of sustainability based on ontological entities. [Paper presentation]. 26th International Conference on Educational Sciences, Antalya, Turkey
<a href = "https://drive.google.com/file/d/1k4JZeJnBb3SNmb3-mlIX0BUjVkmTUlFC/view?usp=share_link" target="_blank"> `r fontawesome::fa(name = "file-lines")`</a>
<a href = "https://drive.google.com/file/d/1zfU0uUB5BJT-DE_O1ZqNy9pTezxk2uvQ/view?usp=share_link" target="_blank">`r fontawesome::fa(name = "desktop")`</a>
</p>

<p>
11. Cengizoglu, S. & **Demirci, S.** (2016). Türkiye’de Yaşayan Çocuklar ve Çevre-İnsan İlişkisi: Bir İçerik Analizi Çalişmasi [Human-Environment Interactions of Children in Turkey: A Content Analysis]. UFBMEK 2016 (National Science and Mathematics Education Congress of Turkey), Trabzon, Turkey
<a href = "https://openaccess.mef.edu.tr/xmlui/bitstream/handle/20.500.11779/514/Bildiri-%C3%96zet-Kitap%C3%A7%C4%B1%C4%9F%C4%B1.pdf?sequence=3&isAllowed=y" target="_blank">`r fontawesome::fa(name = "file-lines")`</a>
</p>

<p>
10. **Demirci, S.** & Cengizoglu, S. (2016). Türkiye’de Okul Öncesi Dönemde Fen Eğitimi’nde Yapilan Çalişmalarin Bölgelere, Değişkenlere ve Örneklem Gruplarina Göre İçerik Analizi [A Content Analysis of Studies in Preschool Science Education in Turkey by Regions, Variables Used and Sample Groups]. [Poster presentation]. UFBMEK 2016, Trabzon, Turkey
<a href= "https://drive.google.com/file/d/1i2xsSsXWxePk80cbvw6usVaHhHh2W_7c/view?usp=share_link" target="_blank">`r fontawesome::fa(name = "chart-pie")`</a>
</p>

<p>
9. **Demirci, S.** & Sahin E. (2016). An Analysis of Turkish Middle School Science Education Program Placing Climate Change Issues in The Context of Education for Sustainable Development. [Paper presentation]. the 14th International JTEFS/BBCC Conference Sustainable Development, Culture, Education: Innovations and Challenges of Teacher Education for Sustainable Development, Konya, Turkey
</p>

<p>
8. **Demirci, S.** (2016). The Context of Sustainable Development in Turkish Elementary Science Curriculum. [Paper presentation]. the 14th International JTEFS/BBCC Conference Sustainable Development, Culture, Education: Innovations and Challenges of Teacher Education for Sustainable Development, Konya, Turkey
</p>

<p>
7. **Demirci, S.**, Sahin E. & Teksoz, G. (2015). Is the Carrying Capacity Exceeded? Preservice Teachers’ Beliefs on Human Population Growth. [Roundtable Discussion]. The annual meeting of North American Association for Environmental Education, San Diego, California, U.S.A.
<a href = "https://drive.google.com/file/d/1e8SUsiPjwaDdaydQV680lpNORPS8fXtz/view?usp=share_link" target="_blank"> `r fontawesome::fa(name = "file-lines")`</a>
</p>

<p>
6. **Demirci, S.**, Sahin E. & Teksoz, G. (2015). An Exploration of University Students’ Beliefs on the Sustainable Growth of Human Population. [Paper presentation]. 8th World Environmental Education Congress (WEEC), Gothenburg, Sweden
<a href = "https://weec2015.weecnetwork.org/" target="_blank">`r fontawesome::fa(name = "link")`</a>
<a href = "https://drive.google.com/file/d/1shuVtXX8W9_Y7PoAr-v1flAtgdeUs3m9/view?usp=share_link" target="_blank"> `r fontawesome::fa(name = "file-lines")`</a>
<a href = "https://drive.google.com/file/d/1cVaG0nS243RMEbYY7oyH-ZRxYWsn9iqR/view?usp=share_link" target="_blank">`r fontawesome::fa(name = "desktop")`</a>
</p>

<p>
5. **Demirci, S.** & Teksoz, G. (2015). ESD in Higher Education: University students’ perceptions of sustainability and its relation to their self-efficacy beliefs to integrate sustainability into their profession and daily lives. [Poster presentation]. the Pathways to the Future: Education for Sustainable Development, Tallinn, Estonia
<a href = "https://drive.google.com/file/d/1VQ_kpGZ6osOIeK2rKH4bj4IJDua9fNxL/view?usp=sharing" target="_blank">`r fontawesome::fa(name = "file-lines")` </a>
<a href= "https://drive.google.com/file/d/1GkD1mCl9Ms2mJqxdOLG352ohNe5aD-Hd/view?usp=share_link" target="_blank">`r fontawesome::fa(name = "chart-pie")`</a>
</p>

<p>
4. **Demirci, S.** & Teksoz, G. (2014). Üniversite Öğrencilerinin Sürdürülebilir Kalkınma Kavramını Gelecekteki Meslekleri Ve Günlük Yaşamlarına Birleştirmek Konusundaki Öz-yeterlik İnanışları. [Paper presentation]. UFBMEK 2014, Adana, Turkey
</p>

<p>
3. **Demirci, S.**, Sahin E. & Teksoz, G. (2014). What does a Survey Study on Beliefs towards Human Population Growth Imply for Teacher Education? [Paper presentation]. EJER 2014 Congress, İstanbul, Turkey
<a href = "https://ejercongress.org/2014/" target="_blank">`r fontawesome::fa(name = "link")`</a>
</p>

<p>
2. **Demirci, S.**, Sahin E. & Teksoz, G. (2013). Determining Pre-service Teachers’ Beliefs towards Human Population Growth. [Roundtable Discussion]. The annual meeting of North American Association for Environmental Education, Baltimore, Maryland, U.S.A.
<a href = "https://drive.google.com/file/d/1JdAmBbiFuCFGvo9JMJKTIuiWE86c3r-c/view?usp=share_link" target="_blank"> `r fontawesome::fa(name = "file-lines")`</a>
<a href = "https://convention2.allacademic.com/one/naaee/naaee13/" target="_blank"> `r fontawesome::fa(name = "link")`</a>
</p>

<p>
1. **Cokoglu, S.** & Sahin, E. (2012). Beliefs toward Population Growth in Turkey. [Paper presentation]. 1. Ulusal Disiplinlerarası Cevre Kongresi, Sakarya, Turkey
</p>


<p><sup>†</sup> Some works are cross-listed under *Science Education* and *Environmental & Sustainability Education*. This is because certain works are relevant to both fields.</p>

