---
title: "Research Experience"
description: null
site: distill::distill_website
---



# Peer Reviewed Publications/Preprints

<p>
4. Demirci S., Dogucu, M. Zieffler A. & Rosenberg, J.M. (2025, Preprint). Understanding Pedagogical Content Knowledge of Data Science Instructors: An Inaugural Framework. <a href = "https://doi.org/10.48550/arXiv.2508.14009" target="_blank"> `r fontawesome::fa(name = "file-lines")`</a>
</p>

<p>
3. Dogucu, M., **Demirci, S.**, Bendekgey, H., Ricci F. Z.,& Medina, C. M.(2025). A Systematic Literature Review of Undergraduate Data Science Education Research. Journal of Statistics and Data Science Education, 1–13. <a href = "https://www.tandfonline.com/doi/full/10.1080/26939169.2025.2486656" target="_blank"> `r fontawesome::fa(name = "file-lines")`</a>
</p>

<p>
2. Demirci, S., & İlk, Ö. (2024). A Comparative Analysis of PISA 2015 Türkiye Studies: Introducing A Variable Selection Model to International Large-Scale Assessments. Van Yüzüncü Yıl University Journal of Education, 21(3), 840-868. <a href = "https://doi.org/10.33711/yyuefd.1539072" target="_blank"> `r fontawesome::fa(name = "file-lines")`</a>  
</p>

<p>
1. Demirci S., Dogucu, M. Zieffler A. & Rosenberg, J.M. (2023). Learning Difficulties of Introductory Data Science Students. In E. Jones (Ed) Proceedings of the International Association for Statistical Education Satellite Conference. Online. <a href = "https://escholarship.org/uc/item/01p3k7f3" target="_blank"> `r fontawesome::fa(name = "file-lines")`</a>
</p>

# Conference Presentations 

<p>
7. Chance, B., **Demirci, S.**, Grove, R., Kandali, V.S., Ravat U.,Truong A. C.  & Wilcox, D. (2026). Measuring and Evoking Curiosity in Statistics/Probability Students [Accepted Oral Presentation]. 12th International Conference on Teaching Statistics, Brisbane, Australia.
</p>


<p>
6. Tackett, M. & **Demirci, S.** (2025). Exploring Faculty Motivation and Practices Using Universal Design for Instruction. Lightning talk presented at RoSE 2025 E-Conference, Online. <a href = "https://www.rose-network.org/events/rose-2025" target="_blank">`r fontawesome::fa(name = "link")`</a> 
</p>

<p>
5. Behroozi, D. Schedler, J. & **Demirci S**. (2025). The Sound of Statistics: Can Sonified Data Elicit an Emotional Response? [Poster Presentation]. Eighth annual Symposium on Data Science and Statistics, The American Statistical Association, Salt Lake City, Utah, U.S.A.
</p>


<p>
4. Demirci, S., Dogucu, M., Rosenberg, J.M. & Zieffler, A. (2024). Crafting University Experiences: Perspectives and Practices in Teaching Introductory Data Science [Topic-Contributed Paper Session]. Joint Statistical Meetings, Portland, Oregon, U.S.A. <a href = "https://ww2.amstat.org/meetings/jsm/2024/index.cfm" target="_blank">`r fontawesome::fa(name = "link")`</a> 
<a href = "https://sinemdemirci.github.io/jsm-24" target="_blank"> `r fontawesome::fa(name = "desktop")`</a>
</p>

<p>
3. Demirci, S., Dogucu, M.,  Bendekgey, H., Ricci F. Z.,& Medina, C. M. (2024). Herding Cats: A Systematic Literature Review on Undergraduate Data Science Education Research [Paper Presentation]. The 2024 Pacific Division Annual Meeting, San Diego, California, U.S.A. <a href = "https://www.canva.com/design/DAGIDPh1m9U/4U8qcM2uWkMiA7O7aCCURQ/view?utm_content=DAGIDPh1m9U&utm_campaign=designshare&utm_medium=link&utm_source=editor" target="_blank"> `r fontawesome::fa(name = "desktop")`</a>
</p>



<p>
2. Dogucu, M., **Demirci, S.**, Bendekgey, H., Ricci F. Z.,& Medina, C. M. (2024). Building Data Science Education Research Plan for Teacher-Scholars [Breakout Session]. Electronic Conference On Teaching Statistics (eCOTS 2024), Online. _Selected as "hot topic of the day"_
<a href = "https://www.causeweb.org/cause/ecots/ecots24" target="_blank">`r fontawesome::fa(name = "link")`</a>
<a href = "https://mdogucu.github.io/eCOTS-2024/" target="_blank"> `r fontawesome::fa(name = "desktop")`</a>
</p>


<p>
1. Demirci S., Dogucu, M. Zieffler A. & Rosenberg, J.M. (2023). Learning Difficulties of Introductory Data Science Students. [Paper presentation]. 13th IASE Satellite Conference, Toronto, Canada.
<a href = "https://iase2023satellite.github.io/speakers.html" target="_blank">`r fontawesome::fa(name = "link")`</a>
  <a href="https://sinemdemirci.github.io/iase-2023/" target="_blank"> `r fontawesome::fa(name = "desktop")`</a>
</p>


# Postdoctoral Research Experience

Postdoctoral Visiting Researcher / Lecturer, 2022 - 2023     
Dept. of Statistical Science, <b> <a href = 'https://www.ucl.ac.uk/statistics/' target="_blank"> University College London </b></a>  
__Postdoc Mentor:__ <a href = 'https:minedogucu.com' target="_blank"> Dr. Mine Dogucu </a>  
