---
title: "Memberships & Services to the Fields"
description: |
site: distill::distill_website
---

## Professional Memberships

|                                                                   | 
| :-------------                                                    | :---------  
| American Statistical Association (ASA)                            | 2023 - 2025
| Associate Fellow, UK Higher Education Academy                        | 2023 - Present
| American Educational Research Association (AERA)                  | 2023
| North American Association for Environmental Education            | 2013 - 2014 & 2015 - 2016



## Journal Peer Reviewing


|                                                           |   
| :-------------                                            | :----  
| Review of Education (BERA)                                | 2025 - Present
| Journal of Statistics and Data Science Education          | 2024 - Present
| Journal of Turkish Science Education                      | 2024
| Environmental Education Research                          | 2022 - Present
| Van Yuzuncu Yil University Journal of Education           | 2022 & 2023
| e-Kafkas Journal of Educational Research                  | 2023 - Present
| E-International Journal of Educational Research           | 2020    




## Services to the Fields

### Statistics and Data Science Education

<p>
4. Judge at Undergraduate Statistics Project Competition and Electronic Undergraduate Statistics, Research Conference, Spring 2023 <a href = "https://www.causeweb.org/usproc/" target="_blank">`r fontawesome::fa(name = "link")`</a>
</p>

<p>
3. Judge at Undergraduate Statistics Project Competition and Electronic Undergraduate Statistics, Research Conference, Fall 2023 <a href = "https://www.causeweb.org/usproc/" target="_blank">`r fontawesome::fa(name = "link")`</a>
</p>

<p>
2. Reviewer at IASE Satellite Conference 2023 Proceedings <a href = "https://iase2023satellite.github.io/" target="_blank">`r fontawesome::fa(name = "link")`</a>
</p>


<p>
1. Judge at Undergraduate Statistics Project Competition and Electronic Undergraduate Statistics, Research Conference, Fall 2022 <a href = "https://www.causeweb.org/usproc/" target="_blank">`r fontawesome::fa(name = "link")`</a>
</p>

### Environmental and Sustainability Education


<p>
4. Reviewer at 2024 AERA Annual Meeting
</p>

<p>
3. Reviewer at 52th Annual NAAEE conference, 2023
</p>

<p>
2. Reviewer at  44th Annual NAAEE Conference, 2015
</p>

<p>
1. Reviewer at  43th Annual NAAEE Conference, 2014
</p>

### Science Education

<p>
8. Volunteer at <a href = "http://obe.metu.edu.tr/en/science-through-art-2019" target="_blank"> Science through ART </a>, The European Researchers' Night event funded under the European Union's Horizon 2020 program, organized by the METU Society and Science Application and Research Center, METU Campus in September 2019
</p>

<p>
7. Volunteer at <a href = "http://obe.metu.edu.tr/en/scienceathome-2017" target="_blank"> Science@Home </a>, The European Researchers' Night event funded under the European Union's Horizon 2020 program, organized by the METU Society and Science Application and Research Center, METU Campus in September 2017
</p>

<p>
6. Volunteer at <a href = "http://obe.metu.edu.tr/en/scienceisfun-2012" target="_blank"> Science is Fun! @METU event </a>, organized by the METU Society and Science Application and Research Center, METU Campus, November 4, 2012
</p>

<p>
5. Jury Member at Science Fair, ODTÜ Geliştirme Vakfı Okulları, Ankara, Turkey, 2020
</p>

<p>
1 - 4. Jury Member at Science Fair, ODTÜ Geliştirme Vakfı Okulları, Ankara, Turkey, 2013 - 2016 
</p>
