---
title: ""
toc: true
---

# Research Mentoring and Academic Service

|  |  |  |
|------------------------|------------------------|-----------------------:|
| Naya Ko (Duke University) | Co-Mentor, Independent Research Project | Sum 2026 |
| Mico Bonanno (Cal Poly) | Co-Mentor, The Frost Summer Undergraduate Research Program (SURP) | Sum 2026 |
| Kendall J. Hipes (Cal Poly) | Master's Thesis Committee Member | 2025 |
| Donya Behroozi | Co-Mentor, Independent Research Project | 2025 |

# Professional Memberships

|  |  |
|:-----------------------------------|-----------------------------------:|
| American Statistical Association (ASA) | 2023–Present |
| Associate Fellow, UK Higher Education Academy | 2023–Present |
| American Educational Research Association (AERA) | 2023 |
| North American Association for Environmental Education (NAAEE) | 2013–2016 |

# Service to the Department

|  |  |  |
|------------------------|------------------------|-----------------------:|
| Member, Curriculum Development Committee, STAT 1110 - Applied Statistical Concepts and Methods | Cal Poly | 2025–Present |
| Course Coordinator, MSE 409 & 410 - Practice Teaching I & II | METU | 2016–2020 |

# Service to the Field

## Statistics and Data Science Education

|  |  |  |
|------------------------|------------------------|-----------------------:|
| The International Turkish Statistical Association (ITSA) Education and Career Development Committee | Chair | 2026 |
| Journal of Statistics and Data Science Education | Reviewer | 2024–Present |
| $12^{\text{th}}$ International Conference on Teaching Statistics (ICOTS12) Proceedings | Reviewer | 2026 |
| Undergraduate Statistics Project Competition and Electronic Undergraduate Statistics Research Conference | Judge | Fall 2025, Spr 2023, Fall 2023, Fall 2022 |
| IASE Satellite Conference Proceedings | Reviewer | 2023 |

## Environmental and Sustainability Education

|  |  |  |
|------------------------|------------------------|-----------------------:|
| Environmental Education Research | Reviewer | 2022–Present |
| American Educational Research Association (AERA) Annual Meeting | Reviewer | 2024 |
| Annual North American Association for Environmental Education (NAAEE) conference | Reviewer | 2023, 2015, 2014 |

## Science Education

|  |  |  |
|------------------------|------------------------|-----------------------:|
| Review of Education (BERA) | Reviewer | 2025 |
| Journal of Turkish Science Education | Reviewer | 2024 |
| Van Yuzuncu Yil University Journal of Education | Reviewer | 2022–2023 |
| e-Kafkas Journal of Educational Research | Reviewer | 2023–2025 |
| E-International Journal of Educational Research | Reviewer | 2020 |
| Science Fair, Middle East Technical University Development Foundation Schools | Judge | 2020 |
| <a href = "http://obe.metu.edu.tr/en/science-through-art-2019" target="_blank"> Science through ART </a>, The European Researchers' Night, European Union's Horizon 2020 program | Volunteer | 2019 |
| <a href = "http://obe.metu.edu.tr/en/scienceathome-2017" target="_blank"> Science\@Home </a>, The European Researchers' Night event funded under the European Union's Horizon 2020 program | Volunteer | 2017 |
| Science Fair, Middle East Technical University Development Foundation Schools | Judge | 2013–2016 |
| <a href = "http://obe.metu.edu.tr/en/scienceisfun-2012" target="_blank"> Science is Fun! @METU event </a>, METU Campus | Volunteer | 2012 |

# Service to the Broader Community

|  |  |  |
|------------------------|------------------------|-----------------------:|
| Charity Event for Middle School Students from Underserved Communities, Ankara, Türkiye | Volunteer | 2022–2023 |
| TED International Education Forum – Digital Obesity, Ankara, Türkiye | Organizing Committee Member | 2021 |
| Weekend Supplementary Classes for Middle School Students from Underserved Communities, “Okula Yüz Verin” project, METU Alumni Assocation, Ankara, | Organizer | 2013–2014 |
| Wheelchair Basketball Charity Event | Event Organization and Ticket Sales | 2010 |
| School Construction Charity Project ("Okula Yüz Verin") Supporting Underserved Communities, METU Alumni Association, Ankara, Türkiye | Volunteer | 2010–2014 |
| Academic Support for Visually Impaired Students, Middle East Technical University, Ankara, Türkiye | Volunteer | 2009–2010 |
| Youth Summer Camp, Middle East Technical University, Ankara, Türkiye | Camp Leader | 2009 |
| *Temiz Eymir* (Clean Eymir): Waste Collection, Sorting, and Recycling Project, Ankara, Türkiye | Volunteer | 2008–2010 |
| UNICEF Card and Gift Sales Campaign | Volunteer | 2006–2010 |
| Annual Charity Events for Elementary School Students from Underserved Communities, Ankara, Türkiye | Volunteer | 2006–2011 |
| METU Scouts Student Club | Member, Leader, and Head of Education Committee | 2006–2011 |
