---
title: ""
toc: true
editor: visual
---

# California Polytechnic State University

## Courses

| **Course Code** | **Course Name** | **Term** |
|:------------------|:-----------------------------|:-----------------------|
| STAT 1110 | Applied Statistical Concepts and Methods | Fall 2026 |
| STAT 218 | Applied Statistics for the Life Sciences | 8 Quarters (2023 - 2026) <a href = "https://stat218-2026.github.io/website/" target="_blank"> {{< fa desktop >}}</a> |
| STAT 130 | Introduction to Statistical Reasoning | 2 Quarters Fall 25 - Win 26) <a href = "https://drive.google.com/file/d/17Vdp4X4jrMDGbvmmmEaIDIQcViE_CEI_/view?usp=sharing" target="_blank">{{< fa file-lines >}}</a> |
| STAT 251 | Statistical Inference for Management I | 2 Quarters (Win 25 - Spr 25) <a href = "https://drive.google.com/file/d/1FKXjGfU2ubt2PAIywTjPZM2gKUPOywGN/view?usp=sharing" target="_blank">{{< fa file-lines >}}</a> |
| STAT 217 | Introduction to Statistical Concepts and Methods | 4 Quarters (Spr 24 - Sum 25) <a href = "https://drive.google.com/file/d/1jsvYDAsTg0Qa1xLSUZcetLK-gxszyaAO/view?usp=sharing" target="_blank">{{< fa file-lines >}}</a> |

# University College London

## Courses

| **Course Code** | **Course Name**                      | **Term**        |
|:----------------|:-------------------------------------|:----------------|
| STAT0004        | Introduction to Practical Statistics | Term 2 (Winter) |

## Responsibilities

Here are some of the tasks I have undertaken as a demonstrator for <b><a href = 'https://www.ucl.ac.uk/module-catalogue/modules/introduction-to-practical-statistics-STAT0004' target ="_blank"> STAT0004 </b></a> at the Department of Statistical Science at UCL, in my role as a (Postdoctoral) Visiting Researcher/Lecturer:

- Facilitating computer practical sessions
- Providing feedback for group homework

# Middle East Technical University

As a teaching/research assistant for 8 academic years, I delivered mostly the tutorials and computer practical sessions of undergraduate and graduate <b><a href = 'https://catalog.metu.edu.tr/prog_courses.php?prog=460' target="_blank"> statistics courses </b></a> in the <b> Department of Mathematics and Science Education </b> at Middle East Technical University <b>(METU)</b>, Ankara, Turkey. I have been also a TA for <b><a href = 'https://catalog.metu.edu.tr/prog_courses.php?prog=460' target="_blank"> graduate research & undergraduate practice teaching courses </b> </a>.

## Courses

| **Course Code** | **Course Name** | **Number of Semesters** |
|:-------------|:-----------------------------------|:-----------------------|
| MSE 501 | Educational Statistics | 8 Semesters (2014 – 2020) |
| MSE 409 & 410 | Practice Teaching, I & II | 6 Semesters (2016 – 2020) |
| MSE 487 | Environmental Science | 5 Semesters (2014 – 2020) |
| MSE 474 | Education and Awareness for Sustainability | 3 Semesters (2014 – 2020) |
| MSE 309 | Statistical Applications in Education | 3 Semesters (2016 – 2020) |
| MSE 305 | Assessment of Learning in Science and Mathematics | 2 Semesters (2014 – 2015) |
| ELE 477 | Laboratory Applications in Environmental Education | 2 Semesters (2012 & 2017) |
| MSE 288 | Community Service | 2 Semesters (2017 – 2019) |
| MSE 502 | Research Methods and Ethics | 1 Semester (Spr 2019) |
| MSE 602 | Advanced Educational Research | 1 Semester (Fall 2016) |
| MSE 475 | Climate Change Education for Sustainability | 1 Semester (Spr 2014) |
| MSE 536 | Skills on Environmental Issue Investigation | 1 Semester (Fall 2014) |
| MSE 301 | Methods of Science Teaching in Middle Schools I | 1 Semester (Spr 2017) |
| MSE 302 | Methods of Science Teaching in Middle Schools II | 1 Semester (Spr 2018) |
| MSE 531 | Readings in Science Education | 1 Semester (Fall 2017) |
| MSE 502 | Research Methods and Ethics | 1 Semester (Spr 2019) |
| MSE 602 | Advanced Educational Research | 1 Semester (Fall 2016) |

## Responsibilities

As a teaching assistant, I contributed to the courses by:

- Delivering tutorials and computer practical sessions
- Creating and revising educational materials for tutorials and computer practical sessions
- Holding office hours
- Grading homework and lesson plans
- Providing personalized feedback for homework, quizzes, exams, and lesson plans
- Facilitating outdoor activities
- Partnering with NGOs to develop and facilitate community engagement activities
