---
title: "Teaching Experience"
description: null
site: distill::distill_website
---

# California Polytechnic State University

| **Course Code**   | **Course Name**                                       | **Term**
| :-------          | :-----------------------                              | :-----------
| STAT 217          | Introduction to Statistical Concepts and Methods      | Summer 2024 `r fontawesome::fa(name = "file-lines")`
| STAT 218          | Applied Statistics for the Life Sciences              | Summer 2024 `r fontawesome::fa(name = "desktop")`
| STAT 217          | Introduction to Statistical Concepts and Methods      | Spring 2024 <a href = "https://drive.google.com/file/d/1jsvYDAsTg0Qa1xLSUZcetLK-gxszyaAO/view?usp=sharing" target="_blank">`r fontawesome::fa(name = "file-lines")`</a>
| STAT 218          | Applied Statistics for the Life Sciences              | Winter 2024 <a href = "https://stat218-wi24.github.io/website/" target="_blank">`r fontawesome::fa(name = "desktop")`</a>
| STAT 218          | Applied Statistics for the Life Sciences              | Fall 2023 <a href = "https://sinemdemirci.github.io/stat-218-fa23/" target="_blank">`r fontawesome::fa(name = "file-lines")`</a>


# University College London


| **Course Code**   | **Course Name**                                       | **Term**
| :-------          | :-----------------------                              | :-----------
| STAT0004       | Introduction to Practical Statistics                     | Term 2 (Winter)


### Tasks

Here are some of the tasks I have undertaken as a demonstrator for <b><a href = 'https://www.ucl.ac.uk/module-catalogue/modules/introduction-to-practical-statistics-STAT0004' target ="_blank"> STAT0004 </b></a> at the Department of  Statistical Science at UCL, in my role as a (Postdoctoral) Visiting Researcher/Lecturer:

  * Facilitating computer practical sessions
  * Providing feedback for group homework

# Middle East Technical University

As a teaching/research assistant for 8 academic years, I delivered mostly the tutorials and computer practical sessions of undergraduate and graduate <b><a href = 'https://catalog.metu.edu.tr/prog_courses.php?prog=460' target="_blank"> statistics courses </b></a> in the <b> Department of Mathematics and Science Education </b> at Middle East Technical University <b>(METU)</b>, Ankara, Turkey. I have been also a TA for <b><a href = 'https://catalog.metu.edu.tr/prog_courses.php?prog=460' target="_blank"> graduate research & undergraduate practice teaching  courses </b> </a>.

| **Course Code**   | **Course Name**                                       | **Number of Semesters**
| :-------          | :-----------------------                              | :-----------
| MSE 501           | Educational Statistics                                | 8 Semesters (2014 – 2020)
| MSE 309           | Statistical Applications in Education                 | 3 Semesters (2016 – 2020) 
| MSE 305           | Assessment of Learning in Science and Mathematics     | 2 Semesters (2014 – 2015)
| MSE 502           | Research Methods and Ethics                           | 1 Semester (Spring 2019)
| MSE 602           | Advanced Educational Research                         | 1 Semester (Fall 2016)
| MSE 409 & 410     | Practice Teaching, I & II                             | 6 Semesters (2016 – 2020)


### Tasks
Some of work I have done as a TA for these courses as following:

  * Delivering tutorials and computer practical sessions
  * Creating and revising educational materials for computer practical sessions
  * Holding office hours
  * Grading homework and assigning grades
  * Providing personalized feedback for homework, quizzes, exams, and lesson plans.